import pyautogui
import time
pyautogui.press("win")
pyautogui.write("word")
pyautogui.press("enter")
time.sleep(2)
pyautogui.press("enter")
pyautogui.write("Alayde Domingues Couto de Macedo",interval=0.1)
pyautogui.hotkey("ctrl","t")
pyautogui.hotkey("ctrl","n")
pyautogui.hotkey("ctrl",">")
pyautogui.hotkey("ctrl",">")
pyautogui.hotkey("ctrl","e")
pyautogui.press("enter")
pyautogui.write("Kimberly da Silva Garcia Teotonio",interval=0.1)